services:
  forum-api:
    build:
      context: .   # Path to your Dockerfile and application code
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Map host port 8080 to container port 8080
    environment:
      DB_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      JWT_SECRET: my-secret-key
    depends_on:
      - mysql
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/local/app/src

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: forum_api
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
